export const testIds = {
  backofficeLoader: 'BACKOFFICE_LOADER',
  moderation: {
    postsFilter: 'POSTS_FILTER',
    moderationList: 'MODERATION_LIST',
    mediaCard: 'MEDIA_CARD',
    no_media: 'NO_MEDIA_FOUND',
    FilterForm: {
      container: 'FILTER_FORM_CONTAINER',
      searchInput: 'FILTER_SEARCH_INPUT',
      sourceInput: 'FILTER_SOURCE_INPUT',
      visibiltyInput: 'FILTER_VISIBILTY_INPUT',
      submitButton: 'FILTER_SUBMIT_BUTTON',
      resetButton: 'FILTER_RESET_BUTTON',
    },
  },
  wallSettings: {
    titleInput: 'TITLE_INPUT',
    fileInput: 'FILE_INPUT',
    submitButton: 'SUBMIT_BUTTON',
    uploadWrapper: 'UPLOAD_WRAPPER',
  },
  sidemenu: {
    container: 'SIDEMENU',
    logo: 'LOGO',
    menuItem: 'MENU_ITEM',
    menuButton: 'MENU_BUTTON',
    userEmail: 'USER_EMAIL',
  },
  announcements: {
    container: 'ANNOUNCEMENT_LIST_CONTAINER',
    addButton: 'ANNOUNCEMENT_ADD_BUTTON',
    addButtonEmpty: 'ANNOUNCEMENT_ADD_BUTTON_EMPTY',
    Spinner: 'ANNOUNCEMENT_SPINNER',
    announcementForm: {
      container: 'ANNOUNCEMENT_FORM',
      closeButton: 'CLOSE_BUTTON',
      submitButton: 'SUBMIT_BUTTON',
      titleInput: 'TITLE_INPUT',
      startDateInput: 'START_DATE_INPUT',
      endDateInput: 'END_DATE_INPUT',
      descriptionInput: 'DESCRIPTION_INPUT',
      form: 'FORM',
    },
    deleteAnnouncementModal: {
      container: 'DELETE_ANNOUNCEMENT_MODAL',
      confirmButton: 'CONFIRM_BUTTON',
      closeButton: 'CLOSE_BUTTON',
    },
    announcementItem: {
      container: 'ITEM_CONTAINER',
      dots: 'DTOS',
      edit: 'EDIT',
      delete: 'DELETE',
    },
  },
  landing: {
    Card: {
      container: 'CARD_CONTAINER',
      pinnedIcon: 'PINNED_ICON',
      backgroundImage: 'BACKGROUND_IMAGE',
      video: 'VIDEO',
      youtubeVideo: 'YOUTUBE-VIDEO',
      socialIcon: 'SOCIAL_ICON',
    },
    AnnouncementOrPost: {
      announcementContainer: 'ANNOUNCEMENT_CONTAINER',
    },
  },
  layout: 'LAYOUT',
  header: 'HEADER',
  logoutBtn: 'HEADER_LOGOUT_BTN',
  modalContainer: 'MODAL_CONTAINER',
  modalCloseBtn: 'MODAL_CLOSE_BTN',
  modalConfirmation: 'MODAL_CONFIRMATION',
  content: 'CONTENT',
  loginPage: 'LOGIN_PAGE',
  auth: {
    email: 'AUTH_EMAIL',
    password: 'AUTH_PASSWORD',
    submitBtn: 'AUTH_SUBMIT',
  },
  frontoffice: {
    header: {
      loader: 'HEADER_LOADER',
      img: 'HEADER_IMG',
      title: 'HEADER_TITLE',
    },
    footer: {
      loader: 'FOOTER_LOADER',
      logo: 'FOOTER_LOGO',
      coOrganizer: 'FOOTER_CO_ORGANIZER',
      institutionalPartners: 'FOOTER_PARTNERS',
      sponsors: 'FOOTER_SPONSORS',
    },
  },
};
