export const MEDIA_DATA = {
  content: [
    {
      id: 'YT-pxnhN_CntIs',
      text: 'Open Mic - DevoxxMA Day 02',
      type: 'VIDEO',
      source: 'YOUTUBE',
      url: 'https://www.youtube.com/embed/pxnhN_CntIs',
      thumbnail: 'https://i.ytimg.com/vi/pxnhN_CntIs/hqdefault.jpg',
      permalink: 'https://www.youtube.com/watch?v=pxnhN_CntIs',
      children: null,
      timestamp: '2022-12-18T13:20:00Z',
      owner: {
        id: 'UCbJ1L2YRk6_CoVbl3_6tBew',
        username: 'BizTech Morocco',
        avatar: null,
      },
      hidden: false,
      pinned: false,
      sourceTypes: ['devoxxma'],
      clean: false,
      analyzed: true,
      textContainsOnlyHashtags: false,
    },
    {
      id: 'YT-QsKKwsmdVnI',
      text: 'Devoxx Morocco s’invite à Agadir2 #shorts',
      type: 'VIDEO',
      source: 'YOUTUBE',
      url: 'https://www.youtube.com/embed/QsKKwsmdVnI',
      thumbnail: 'https://i.ytimg.com/vi/QsKKwsmdVnI/hqdefault.jpg',
      permalink: 'https://www.youtube.com/watch?v=QsKKwsmdVnI',
      children: null,
      timestamp: '2023-05-02T15:12:04Z',
      owner: {
        id: 'UCI0vjipQEOBnEQDNzato2Aw',
        username: 'Ayoub Ihyadn',
        avatar: null,
      },
      hidden: false,
      pinned: false,
      sourceTypes: [],
      clean: false,
      analyzed: null,
      textContainsOnlyHashtags: false,
    },
  ],
  pageable: {
    sort: [],
    offset: 0,
    pageNumber: 0,
    pageSize: 2,
    paged: true,
    unpaged: false,
  },
  last: false,
  totalPages: 23,
  totalElements: 459,
  size: 2,
  number: 0,
  sort: [],
  first: true,
  numberOfElements: 2,
  empty: false,
};

export const MEDIA_FILTER_KEYWORD = {
  content: [
    {
      id: 'YT-IeZ5q-u2vPo',
      text: 'Devoxx Morocco test #shorts',
      type: 'VIDEO',
      source: 'YOUTUBE',
      url: 'https://www.youtube.com/embed/IeZ5q-u2vPo',
      thumbnail: 'https://i.ytimg.com/vi/IeZ5q-u2vPo/hqdefault.jpg',
      permalink: 'https://www.youtube.com/watch?v=IeZ5q-u2vPo',
      children: null,
      timestamp: '2023-05-02T15:02:20Z',
      owner: {
        id: 'UCI0vjipQEOBnEQDNzato2Aw',
        username: 'Keyword test',
        avatar: null,
      },
      hidden: false,
      pinned: false,
      sourceTypes: [],
      clean: false,
      analyzed: null,
      textContainsOnlyHashtags: false,
    },
  ],
  pageable: {
    sort: [
      {
        direction: 'DESC',
        property: 'timestamp',
        ignoreCase: false,
        nullHandling: 'NATIVE',
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageSize: 15,
    pageNumber: 0,
    paged: true,
    unpaged: false,
  },
  totalElements: 1,
  totalPages: 1,
  last: true,
  size: 15,
  number: 0,
  sort: [
    {
      direction: 'DESC',
      property: 'timestamp',
      ignoreCase: false,
      nullHandling: 'NATIVE',
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const MEDIA_FILTER_TYPE = {
  content: [
    {
      id: 'YT-IeZ5q-u2vxyz',
      text: 'Devoxx Morocco test #shorts',
      type: 'VIDEO',
      source: 'YOUTUBE',
      url: 'https://www.youtube.com/embed/IeZ5q-u2vPo',
      thumbnail: 'https://i.ytimg.com/vi/IeZ5q-u2vPo/hqdefault.jpg',
      permalink: 'https://www.youtube.com/watch?v=IeZ5q-u2vPo',
      children: null,
      timestamp: '2023-05-02T15:02:20Z',
      owner: {
        id: 'UCI0vjipQEOBnEQDNzato2Aw',
        username: 'Keyword test',
        avatar: null,
      },
      hidden: false,
      pinned: false,
      sourceTypes: [],
      clean: false,
      analyzed: null,
      textContainsOnlyHashtags: false,
    },
  ],
  pageable: {
    sort: [
      {
        direction: 'DESC',
        property: 'timestamp',
        ignoreCase: false,
        nullHandling: 'NATIVE',
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageSize: 15,
    pageNumber: 0,
    paged: true,
    unpaged: false,
  },
  totalElements: 1,
  totalPages: 1,
  last: true,
  size: 15,
  number: 0,
  sort: [
    {
      direction: 'DESC',
      property: 'timestamp',
      ignoreCase: false,
      nullHandling: 'NATIVE',
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};
