import { UserData } from '../../../../types';

export const admins: UserData[] = [
  {
    id: 'user001',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    authorities: [{ id: '1', name: 'ADMIN' }],
    activated: true,
    createdAt: new Date('2023-01-01'),
    lastModifiedAt: new Date('2023-01-15'),
  },
  {
    id: 'user002',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
    authorities: [{ id: '1', name: 'MODERATOR' }],
    activated: true,
    createdAt: new Date('2023-02-10'),
    lastModifiedAt: new Date('2023-06-25'),
  },
  {
    id: 'user003',
    firstName: 'Michael',
    lastName: 'Johnson',
    email: 'michael.johnson@example.com',
    authorities: [{ id: '1', name: 'MODERATOR' }],
    activated: false,
    createdAt: new Date('2023-03-05'),
    lastModifiedAt: new Date('2023-07-20'),
  },
  {
    id: 'user004',
    firstName: 'Emily',
    lastName: 'Brown',
    email: 'emily.brown@example.com',
    authorities: [{ id: '1', name: 'MODERATOR' }],
    activated: true,
    createdAt: new Date('2023-04-12'),
    lastModifiedAt: new Date('2023-07-30'),
  },
  {
    id: 'user005',
    firstName: 'Daniel',
    lastName: 'Wilson',
    email: 'daniel.wilson@example.com',
    authorities: [{ id: '1', name: 'ADMIN' }],
    activated: true,
    createdAt: new Date('2023-05-20'),
    lastModifiedAt: new Date('2023-07-31'),
  },
  {
    id: 'user006',
    firstName: 'Sophia',
    lastName: 'Lee',
    email: 'sophia.lee@example.com',
    authorities: [{ id: '1', name: 'MODERATOR' }],
    activated: true,
    createdAt: new Date('2023-06-08'),
    lastModifiedAt: new Date('2023-07-15'),
  },
  {
    id: 'user007',
    firstName: 'David',
    lastName: 'Anderson',
    email: 'david.anderson@example.com',
    authorities: [{ id: '1', name: 'MODERATOR' }],
    activated: true,
    createdAt: new Date('2023-07-03'),
    lastModifiedAt: new Date('2023-07-25'),
  },
  {
    id: 'user008',
    firstName: 'Olivia',
    lastName: 'Martinez',
    email: 'olivia.martinez@example.com',
    authorities: [{ id: '1', name: 'MODERATOR' }],
    activated: false,
    createdAt: new Date('2023-07-18'),
    lastModifiedAt: new Date('2023-07-18'),
  },
  {
    id: 'user009',
    firstName: 'James',
    lastName: 'Thompson',
    email: 'james.thompson@example.com',
    authorities: [{ id: '1', name: 'MODERATOR' }],
    activated: true,
    createdAt: new Date('2023-08-01'),
    lastModifiedAt: new Date('2023-08-01'),
  },
  {
    id: 'user010',
    firstName: 'Ava',
    lastName: 'Garcia',
    email: 'ava.garcia@example.com',
    authorities: [{ id: '1', name: 'ADMIN' }],
    activated: true,
    createdAt: new Date('2023-08-07'),
    lastModifiedAt: new Date('2023-08-07'),
  },
];
